package compose.icons.simpleicons

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType.Companion.NonZero
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap.Companion.Butt
import androidx.compose.ui.graphics.StrokeJoin.Companion.Miter
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.ImageVector.Builder
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import compose.icons.SimpleIcons

public val SimpleIcons.Ratatui: ImageVector
    get() {
        if (_ratatui != null) {
            return _ratatui!!
        }
        _ratatui = Builder(name = "Ratatui", defaultWidth = 24.0.dp, defaultHeight = 24.0.dp,
                viewportWidth = 24.0f, viewportHeight = 24.0f).apply {
            path(fill = SolidColor(Color(0xFF000000)), stroke = null, strokeLineWidth = 0.0f,
                    strokeLineCap = Butt, strokeLineJoin = Miter, strokeLineMiter = 4.0f,
                    pathFillType = NonZero) {
                moveTo(8.16f, 13.92f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(0.48f)
                lineTo(12.0f, 17.28f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(0.48f)
                lineTo(18.24f, 24.0f)
                lineTo(2.4f, 24.0f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(-0.48f)
                lineTo(0.96f, 22.56f)
                verticalLineToRelative(-0.48f)
                lineTo(0.48f, 22.08f)
                verticalLineToRelative(-0.48f)
                lineTo(0.0f, 21.6f)
                verticalLineToRelative(-0.96f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(0.96f)
                close()
                moveTo(7.2f, 20.64f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(-0.96f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(-0.48f)
                lineTo(7.2f, 19.68f)
                close()
                moveTo(7.2f, 17.76f)
                lineTo(5.76f, 17.76f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(1.92f)
                lineTo(8.16f, 16.8f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(-0.48f)
                lineTo(7.2f, 16.32f)
                close()
                moveTo(24.0f, 7.68f)
                horizontalLineToRelative(-0.48f)
                lineTo(23.52f, 9.6f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(-0.96f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(-0.48f)
                lineTo(20.64f, 12.0f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(-0.96f)
                verticalLineToRelative(4.32f)
                horizontalLineToRelative(2.4f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(4.32f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(0.96f)
                horizontalLineToRelative(-0.48f)
                lineTo(20.16f, 24.0f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(-2.4f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(-1.44f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(1.44f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(-0.48f)
                lineTo(12.0f, 16.32f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(-0.96f)
                lineTo(12.0f, 14.88f)
                verticalLineToRelative(-0.96f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(-0.96f)
                verticalLineToRelative(0.48f)
                lineTo(9.6f, 13.92f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(-0.96f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(0.96f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(3.36f)
                lineTo(13.44f, 9.6f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(0.48f)
                lineTo(15.84f, 7.2f)
                horizontalLineToRelative(1.92f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(1.44f)
                verticalLineToRelative(-0.48f)
                lineTo(24.0f, 6.24f)
                close()
                moveTo(15.84f, 8.64f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(0.96f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(0.96f)
                lineTo(16.8f, 9.6f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(-0.96f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(-0.96f)
                close()
                moveTo(13.92f, 0.48f)
                horizontalLineToRelative(0.48f)
                lineTo(14.4f, 4.8f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(0.96f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(0.96f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(0.48f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(0.48f)
                lineTo(12.0f, 9.6f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(-0.96f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(-0.48f)
                lineTo(9.6f, 7.68f)
                lineTo(9.6f, 7.2f)
                lineTo(6.72f, 7.2f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(-0.48f)
                verticalLineToRelative(-2.4f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(0.48f)
                lineTo(8.16f, 2.4f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(0.48f)
                verticalLineToRelative(-0.48f)
                horizontalLineToRelative(0.48f)
                lineTo(9.6f, 0.96f)
                horizontalLineToRelative(0.48f)
                lineTo(10.08f, 0.48f)
                horizontalLineToRelative(0.96f)
                lineTo(11.04f, 0.0f)
                horizontalLineToRelative(2.88f)
                close()
            }
        }
        .build()
        return _ratatui!!
    }

private var _ratatui: ImageVector? = null
