package compose.icons.simpleicons

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType.Companion.NonZero
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap.Companion.Butt
import androidx.compose.ui.graphics.StrokeJoin.Companion.Miter
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.ImageVector.Builder
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import compose.icons.SimpleIcons

public val SimpleIcons.Supercell: ImageVector
    get() {
        if (_supercell != null) {
            return _supercell!!
        }
        _supercell = Builder(name = "Supercell", defaultWidth = 24.0.dp, defaultHeight = 24.0.dp,
                viewportWidth = 24.0f, viewportHeight = 24.0f).apply {
            path(fill = SolidColor(Color(0xFF000000)), stroke = null, strokeLineWidth = 0.0f,
                    strokeLineCap = Butt, strokeLineJoin = Miter, strokeLineMiter = 4.0f,
                    pathFillType = NonZero) {
                moveTo(6.997f, 21.76f)
                lineTo(0.0f, 21.76f)
                verticalLineToRelative(-1.583f)
                horizontalLineToRelative(0.673f)
                verticalLineToRelative(-3.01f)
                lineTo(0.0f, 17.167f)
                verticalLineToRelative(-1.592f)
                horizontalLineToRelative(6.997f)
                lineToRelative(0.68f, 0.747f)
                verticalLineToRelative(2.14f)
                lineTo(5.759f, 18.462f)
                verticalLineToRelative(-1.296f)
                lineTo(3.134f, 17.166f)
                verticalLineToRelative(0.927f)
                horizontalLineToRelative(1.132f)
                verticalLineToRelative(1.15f)
                lineTo(3.134f, 19.243f)
                verticalLineToRelative(0.934f)
                horizontalLineToRelative(2.624f)
                verticalLineToRelative(-1.296f)
                horizontalLineToRelative(1.92f)
                verticalLineToRelative(2.14f)
                close()
                moveTo(6.997f, 15.08f)
                lineTo(0.0f, 15.08f)
                lineTo(0.0f, 13.5f)
                horizontalLineToRelative(0.673f)
                verticalLineToRelative(-3.01f)
                lineTo(0.0f, 10.49f)
                lineTo(0.0f, 8.896f)
                horizontalLineToRelative(6.997f)
                lineToRelative(0.68f, 0.747f)
                verticalLineToRelative(2.14f)
                lineTo(5.759f, 11.783f)
                verticalLineToRelative(-1.296f)
                lineTo(3.134f, 10.487f)
                verticalLineToRelative(0.927f)
                horizontalLineToRelative(1.132f)
                verticalLineToRelative(1.149f)
                lineTo(3.134f, 12.563f)
                verticalLineToRelative(0.934f)
                horizontalLineToRelative(2.624f)
                verticalLineToRelative(-1.295f)
                horizontalLineToRelative(1.92f)
                verticalLineToRelative(2.14f)
                close()
                moveTo(6.487f, 8.43f)
                horizontalLineToRelative(-4.29f)
                lineToRelative(-0.507f, -0.54f)
                lineToRelative(-0.451f, 0.542f)
                lineTo(0.0f, 8.432f)
                lineTo(0.0f, 6.545f)
                horizontalLineToRelative(1.73f)
                verticalLineToRelative(0.534f)
                horizontalLineToRelative(3.232f)
                verticalLineToRelative(-0.903f)
                lineTo(1.116f, 6.176f)
                lineTo(0.0f, 5.15f)
                lineTo(0.0f, 3.625f)
                lineToRelative(1.28f, -1.378f)
                horizontalLineToRelative(3.854f)
                lineToRelative(0.509f, 0.542f)
                lineToRelative(0.45f, -0.542f)
                horizontalLineToRelative(1.24f)
                verticalLineToRelative(1.887f)
                lineTo(5.6f, 4.134f)
                lineTo(5.6f, 3.6f)
                lineTo(2.674f, 3.6f)
                verticalLineToRelative(0.902f)
                horizontalLineToRelative(3.748f)
                lineToRelative(1.263f, 1.19f)
                verticalLineToRelative(1.443f)
                close()
                moveTo(23.317f, 21.76f)
                lineTo(16.31f, 21.76f)
                verticalLineToRelative(-1.584f)
                horizontalLineToRelative(0.672f)
                verticalLineToRelative(-3.01f)
                horizontalLineToRelative(-0.672f)
                verticalLineToRelative(-1.592f)
                horizontalLineToRelative(3.805f)
                verticalLineToRelative(1.592f)
                horizontalLineToRelative(-0.672f)
                verticalLineToRelative(3.01f)
                horizontalLineToRelative(2.636f)
                verticalLineToRelative(-1.997f)
                horizontalLineToRelative(1.92f)
                verticalLineToRelative(2.842f)
                close()
                moveTo(15.16f, 21.76f)
                lineTo(8.153f, 21.76f)
                verticalLineToRelative(-1.583f)
                horizontalLineToRelative(0.673f)
                verticalLineToRelative(-3.01f)
                horizontalLineToRelative(-0.673f)
                verticalLineToRelative(-1.592f)
                horizontalLineToRelative(3.806f)
                verticalLineToRelative(1.592f)
                horizontalLineToRelative(-0.673f)
                verticalLineToRelative(3.01f)
                horizontalLineToRelative(2.636f)
                lineTo(13.922f, 18.18f)
                horizontalLineToRelative(1.92f)
                verticalLineToRelative(2.842f)
                close()
                moveTo(22.612f, 15.08f)
                horizontalLineToRelative(-4.676f)
                lineToRelative(-1.615f, -1.581f)
                verticalLineToRelative(-3.02f)
                lineToRelative(1.616f, -1.584f)
                horizontalLineToRelative(3.684f)
                lineToRelative(0.459f, 0.575f)
                lineToRelative(0.45f, -0.575f)
                lineTo(24.0f, 8.895f)
                lineTo(24.0f, 11.5f)
                horizontalLineToRelative(-1.92f)
                verticalLineToRelative(-1.02f)
                horizontalLineToRelative(-3.24f)
                verticalLineToRelative(3.02f)
                horizontalLineToRelative(3.24f)
                verticalLineToRelative(-1.04f)
                horizontalLineToRelative(1.919f)
                verticalLineToRelative(1.27f)
                close()
                moveTo(21.555f, 3.829f)
                horizontalLineToRelative(-2.1f)
                verticalLineToRelative(1.083f)
                horizontalLineToRelative(2.1f)
                close()
                moveTo(23.031f, 5.986f)
                horizontalLineToRelative(-3.576f)
                verticalLineToRelative(0.853f)
                horizontalLineToRelative(0.673f)
                verticalLineToRelative(1.584f)
                horizontalLineToRelative(-3.806f)
                lineTo(16.322f, 6.839f)
                horizontalLineToRelative(0.672f)
                verticalLineToRelative(-3.01f)
                horizontalLineToRelative(-0.672f)
                verticalLineToRelative(-1.59f)
                horizontalLineToRelative(6.595f)
                lineToRelative(1.082f, 1.082f)
                verticalLineToRelative(1.698f)
                close()
                moveTo(15.259f, 3.836f)
                verticalLineToRelative(3.233f)
                lineToRelative(-1.37f, 1.362f)
                horizontalLineToRelative(-3.69f)
                lineTo(8.836f, 7.069f)
                lineTo(8.836f, 3.837f)
                horizontalLineToRelative(-0.673f)
                lineTo(8.163f, 2.246f)
                horizontalLineToRelative(3.724f)
                verticalLineToRelative(1.59f)
                horizontalLineToRelative(-0.59f)
                verticalLineToRelative(3.01f)
                horizontalLineToRelative(2.083f)
                verticalLineToRelative(-3.01f)
                horizontalLineToRelative(-0.509f)
                verticalLineToRelative(-1.59f)
                horizontalLineToRelative(2.97f)
                verticalLineToRelative(1.59f)
                close()
                moveTo(12.697f, 10.486f)
                horizontalLineToRelative(-1.41f)
                verticalLineToRelative(1.026f)
                horizontalLineToRelative(1.41f)
                close()
                moveTo(13.378f, 15.079f)
                lineTo(12.698f, 14.399f)
                lineTo(12.698f, 12.47f)
                horizontalLineToRelative(-1.412f)
                verticalLineToRelative(1.025f)
                horizontalLineToRelative(0.5f)
                verticalLineToRelative(1.583f)
                lineTo(8.154f, 15.078f)
                verticalLineToRelative(-1.583f)
                horizontalLineToRelative(0.673f)
                verticalLineToRelative(-3.01f)
                horizontalLineToRelative(-0.673f)
                verticalLineToRelative(-1.59f)
                horizontalLineToRelative(6.078f)
                lineToRelative(1.026f, 1.025f)
                verticalLineToRelative(1.28f)
                lineToRelative(-0.911f, 0.68f)
                lineToRelative(0.91f, 0.69f)
                verticalLineToRelative(1.148f)
                horizontalLineToRelative(0.575f)
                verticalLineToRelative(1.361f)
                close()
            }
        }
        .build()
        return _supercell!!
    }

private var _supercell: ImageVector? = null
